[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pytest_skip_slow"
authors = [{name = "Nag", email = "nag@mail.com"}]
dynamic = ["version", "description"]
